name: Polybot Infrastructure Destroy Terraform

on:
  workflow_dispatch:
    inputs:
      us-east-2:
        description: 'Ohio (us-east-2)'
        required: false
        type: boolean
      eu-west-3:
        description: 'Paris (eu-west-3)'
        required: false
        type: boolean

jobs:
  Terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region:
          - us-east-2
          - eu-west-3
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set AWS Credentials
        id: set-aws-credentials
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets[ 'AWS_ACCESS_KEY_ID_' + matrix.region ] }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets[ 'AWS_SECRET_ACCESS_KEY_' + matrix.region ] }}" >> $GITHUB_ENV
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets['AWS_ACCESS_KEY_ID_' + matrix.region] }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets['AWS_SECRET_ACCESS_KEY_' + matrix.region] }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.0

      - name: Initialize Terraform
        working-directory: tf
        run: terraform init

      - name: Select Workspace and Destroy Infrastructure
        if: ${{ github.event.inputs[matrix.region] == 'true' }}
        working-directory: tf
        run: |
          terraform workspace select ${{ matrix.region }} || terraform workspace new ${{ matrix.region }}
          terraform destroy -auto-approve -var-file=region.${{ matrix.region }}.tfvars
