name: Polybot Infrastructure Destroy Terraform

on:
  workflow_dispatch:
    inputs:
      us-east-2:
        description: 'Ohio (us-east-2)'
        required: false
        type: boolean
      eu-west-3:
        description: 'Paris (eu-west-3)'
        required: false
        type: boolean

jobs:
  Terraform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        region: [us-east-2, eu-west-3]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set AWS Credentials (us-east-2)
        if: ${{ matrix.region == 'us-east-2' }}
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.US_EAST_2_AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.US_EAST_2_AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Set AWS Credentials (eu-west-3)
        if: ${{ matrix.region == 'eu-west-3' }}
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.EU_WEST_3_AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.EU_WEST_3_AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.0

      - name: Initialize Terraform
        working-directory: tf
        run: terraform init

      - name: Select Workspace and Destroy Infrastructure
        if: ${{ github.event.inputs[matrix.region] }}
        working-directory: tf
        run: |
          terraform workspace select ${{ matrix.region }} || terraform workspace new ${{ matrix.region }}
          terraform destroy -auto-approve -var-file=region.${{ matrix.region }}.tfvars