---
name: Yolo5 Microservice Deployment
on:
  push:
    paths:
      - yolo5/**
    branches:
      - main
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2
      - name: Build and push image
        run: |
          cd yolo5 
           # Login to DockerHub (comment out if you don't use DockerHub):
