name: Yolo5 Deployment

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build and push Docker image
      run: |
        cd yolo5
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/yolo5:latest .
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/yolo5:latest

    - name: Get EC2 instance ID
      run: |
         INSTANCE_ID=$(aws autoscaling describe-auto-scaling-instances --query "AutoScalingInstances[0].InstanceId" --output text)
          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
    - name: Get EC2 public IP
      id: get_public_ip
      run: |
        EC2_PUBLIC_IP=$(aws ec2 describe-instances --instance-ids ${{ env.INSTANCE_ID }} --query "Reservations[0].Instances[0].PublicIpAddress" --output text)
        echo "EC2_PUBLIC_IP=$EC2_PUBLIC_IP" >> $GITHUB_ENV

    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.EC2_PUBLIC_IP }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |      
          sudo docker pull '${{ secrets.DOCKERHUB_USERNAME }}/yolo5:latest'
          sudo docker stop yolo5* || true
          sudo docker rm yolo5* || true
          sudo docker run -d --name yolo5 "${{ secrets.DOCKERHUB_USERNAME }}/yolo5:latest" | base64 -w 0
      env:
        AWS_REGION: ${{ secrets.AWS_REGION }}